package org.bamburov.messages;

public class EnglishMessages implements Messages {
    @Override
    public String getFirstStartMessageFormat() {
        return "Hello, %s! I'll let you know when the products you are interested in will become cheaper. Use /help command to get more details.";
    }

    @Override
    public String getSetLinksMessage() {
        return "Enter products links which you want to be cheaper.\nEach link should start with new line.\nYou can view the list of supported sites using the /show_acceptable_sites command";
    }

    @Override
    public String getLinksAcceptedMessageFormat() {
        return "Congrats! Links below are accepted\n%s\nI will let you know when any of this products became cheaper.";
    }

    @Override
    public String getHelpMessage() {
        return "I will notify you when the price of the product you are interested in the online store becomes cheaper. Use the /set_links command to enter links of the products you are interested in. Use the /show_acceptable_sites command to see the list of supported online stores. The maximum allowed number of links is 10. Each link should start on a new line.\n\n" +
                "I have support for 3 languages: English, Serbian and Russian. Use the /set_language command to select a language.\n\n" +
                "My functionality is available by subscription. You can find out your last subscription day using the /get_the_last_day_of_subscription command. The first time you interact with me, you are given a welcome week. To renew your subscription, use the /buy_subscription command or enter a promo code using the /enter_promo command.\n\n" +
                "About promo codes. You can generate them yourself \ud83d\ude42 using the /generate_promo command. But the promo code you generated must be used by another user. As soon as he applies the promo code, both you and he will receive one week of subscription. You cannot use a promo code that you have generated yourself. Promo codes are one-time use and cannot be reused." +
                "You cannot apply a new promo code from another user if you have already successfully applied a promo code from this user. Also, if you successfully applied a promo code from another user, then this user cannot apply the promo code that you generate.\n\n" +
                "Feel free to email postao.jeftiniji@gmail.com if you find a bug, or if your desired site is not yet supported. The developer will add support for your site \ud83d\ude42";
    }

    @Override
    public String getPromoCreatedMessageFormat() {
        return "%s promo code is generated. You will get 1 week free when your friend use it.";
    }

    @Override
    public String getEnterPromoMessage() {
        return "Please, enter a promo code.";
    }

    @Override
    public String getEnteredPromoIsNotValidMessage() {
        return "Entered promo code is not valid. Please try to enter promo code again.";
    }

    @Override
    public String getEnteredPromoDoesNotExistMessage() {
        return "Entered promo code does not exist. Please try to enter promo code again.";
    }

    @Override
    public String getYouCantUsePromoThatWasGeneratedByYouMessage() {
        return "You can't use the promo code which was generated by you \ud83d\ude42 Please try to enter promo code again.";
    }

    @Override
    public String getYouAlreadyUsedPromoFromThatUserMessageFormat() {
        return "You have already used the promo code from %s user. And you can't do it again. Please try to enter promo code again.";
    }

    @Override
    public String getYouUsePromoFromThatUserBecauseThatUserUsedThePromoGeneratedByYouMessageFormat() {
        return "User %s has already applied the promo code that was generated by you. That is why you can't apply promo codes from that user. Please try to enter promo code again.";
    }

    @Override
    public String getPromoIsAppliedSuccessfullyMessage() {
        return "Promo code was applied successfully. You received 1 more week for free! Now your the last day of subscription is %s";
    }

    @Override
    public String getYourFriendSuccessfullyAppliedYourPromoMessageFormat() {
        return "Your friend applied your promo code successfully. You received 1 more week for free!";
    }

    @Override
    public String getSelectLanguageMessage() {
        return "Select language.";
    }

    @Override
    public String getLanguageIsSelectedMessage() {
        return "English language is selected.";
    }

    @Override
    public String getFollowingLinksAreInvalidMessageFormat() {
        return "Following link(s) are invalid:\n%s\nPlease enter links again.";
    }

    @Override
    public String getIsNotAValidLink() {
        return " is not a valid link.";
    }

    @Override
    public String getLinkOfThatSiteIsNotSupportedMessage() {
        return " link of that site is not supported. You can view the list of supported sites using the /show_acceptable_sites command";
    }

    @Override
    public String getTheLastDayOfSubscriptionMessageFormat() {
        return "The last day of subscription is %s";
    }

    @Override
    public String getMaxCountOfLinksMessage() {
        return "Maximum allowed count of links is 10.\nPlease enter links again.";
    }

    @Override
    public String getOneMonthMessage() {
        return "1 month";
    }

    @Override
    public String getThreeMonthsMessage() {
        return "3 months";
    }

    @Override
    public String getSixMonthsMessage() {
        return "6 months";
    }

    @Override
    public String getBuySubscriptionMessage() {
        return "For now only PayPal payment is available\\.\nPlease select payment period\\.\n1 month \\- €3\\.99\n3 months \\- ~€11\\.99~ €9\\.99\n6 months \\- ~€23\\.99~ €17\\.99";
    }

    @Override
    public String getSendPaypalEmailMessage() {
        return "Please enter your PayPal email.";
    }

    @Override
    public String getInvoiceIsGeneratedMessage(String invoiceLink) {
        return "Invoice is generated.\n" + invoiceLink + "\nYour subscription will be prolonged as soon as invoice is paid.";
    }

    @Override
    public String getYouEnteredInvalidPaymentPeriodMessageFormat() {
        return "Entered payment periods are invalid. Valid payment periods are %s, %s, and %s.\nPlease try to enter payment period again.";
    }

    @Override
    public String getYouEnteredInvalidPaypalEmailMessage() {
        return "Entered PayPal email is not valid.\nPlease try to enter PayPal email again.";
    }

    @Override
    public String getYouEnteredInvalidLanguageMessageFormat() {
        return "Entered language is invalid. Valid languages are %s, %s, %s.\nPlease try to enter language again.";
    }

    @Override
    public String getMaxCountOfPromosMessage() {
        return "Maximum allowed count of unused promos that were generated by you is 10.\nUse /show_my_promos command to see full list of unused promos that were generated by you.";
    }

    @Override
    public String getYourPromosMessageFormat() {
        return "List of unused promos that were generated by you.\n%s";
    }

    @Override
    public String getRetrievedPriceMessage() {
        return "Retrieved price";
    }

    @Override
    public String getCheckingLinksMessage() {
        return "Checking links...";
    }
}
